### ISSUE TITLE
estructura de la app

### ISSUE THREAD

**Issue by manelcc** [adrianfanjul/LoginFragments#1]
@adrianfanjul perfecto la separación en packages, una mejora.

Pon las configuraciones de las vistas en una package features

![image](https://user-images.githubusercontent.com/56276965/161443417-75382f51-a13c-4350-9f8a-93cf119fb9ff.png)
 así hacemos que home-login-onboarding estén dentro del package features.

**Comment by adrianfanjul** [comment]
Solucionado
